// @ts-ignore

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { ReactProps } from "@react-three/fiber";
import { Group } from "three";
import { getCdnAsset } from "@/utils/cdn/cdnAssets";

export function Model(props: ReactProps<Group>) {
  const { nodes, materials } = useGLTF(
    getCdnAsset("media/site/logo/initials_logo_3d_glass_glb"),
  );
  return (
    <group {...props} dispose={null}>
      <group rotation={[0, Math.PI / 4, 0]} scale={[0.079, -0.079, 0.079]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0.geometry}
          material={nodes.mesh_0.material}
          position={[-630, -630, -30.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_1.geometry}
          material={nodes.mesh_1.material}
          position={[-630, -630, -30.5]}
          scale={[1.01, 1.01, 1.06]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_2.geometry}
          material={nodes.mesh_2.material}
          position={[-630, -630, -30.5]}
          scale={[1.01, 1.01, 1.06]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_3.geometry}
          material={nodes.mesh_3.material}
          position={[-630, -630, -30.5]}
          scale={[1.01, 1.01, 1.06]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_4.geometry}
          material={nodes.mesh_4.material}
          position={[-630, -630, -30.5]}
          scale={[1.01, 1.01, 1.06]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/initials_logo.gltf");
